# -*- coding: utf-8 -*-
"""BJ10951.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QC5DXa2r-nDXxJbujyq2cOX_LoJ759IO
"""

# 문제 : A+B - 4

while True:
  try:
    A, B = input().split()
    print(int(A)+int(B))
  except (ValueError, EOFError):
    break